./" Página del manual para adminLibro
.TH adminLibro 1 "30/08/2020" "adminLibro" "1.1" "man adminLibro"

.SH NOMBRE
adminLibro \- Administrador libros

.SH SINOPSIS
adminLibro [-a | -t | -h | RTFM] \- autor, título, ayuda y manual.

.SH DESCRIPCIÓN
Un programa sencillo que sirve para guardar, consultar y modificar datos de libros en una biblioteca o librería.
Guarda los data en ~/.local/share/LIBROS.db, este archivo es creado por el makefile y en caso de que sea eliminado o no se haya creado
correctamente, el programa mostrará un mensaje de advertencia.

.SH OPCIONES
.IP "-a\tBúsqueda por autor."
.IP "-t\tBúsqueda por título."
.IP "-h\tAbre una pequeña ventana de ayuda"
.IP "RTFM\tAbre el manual, la puse como una broma."

.SH EJEMPLOS
.IP "adminLibro -a Juan Rulfo\t Busca libros del autor Juan Rulfo"
.IP "adminLibro -t 1984 \t\t Busca libros con el título 1984"
.IP "adminLibro -h \t\t\t Abre una página de ayuda"
.IP "adminLibro RTFM \t\t Opción de broma que abre el manual"

.SH AUTOR
Axel Morales Torres (axelmorales06@hotmail.com)