./" Página del manual para adminLibro
.TH adminLibro 7 "30/08/2020" "adminLibro" "1.0" "man adminLibro"

.SH NAME
adminLibro \- Administrador libros

.SH SYNOPSIS
adminLibro [-a | -t | -h | RTFM] \. autor, título, ayuda y manual.

.SH DESCRIPTION
Un programa sencillo que sirve para guardar, consultar y modificar
datos de libros en una biblioteca o librería.

.SH OPTIONS
.IP -a
Búsqueda por autor.
.IP -t
Búsqueda por título.
.IP -h
Abre una pequeña ventana de ayuda-
.IP RTFM
Abre el manual, la puse como una broma.

.SH EXAMPLES
.IP adminLibro -a "Juan Rulfo"  \- Busca libros del autor "Juan Rulfo"
.IP adminLibro -t "1984" \- Busca libros con el título "1984"
.IP adminLibro -h \- Abre una página de ayuda
.IP adminLibro RTFM \- Opción de broma que abre el manual

.SH AUTHOR
Axel Morales Torres (axelmorales06@hotmail.com)